version: '3'

services:
  web:
    build: .
    ports:
        - "5000:5000"
    volumes:
    - .:/football_player_manager
    depends_on:
      - redis
      - db
    command:
        sh "./start_code.sh"
    environment:
      MYSQL_DATABASE: football_players_db
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_ROOT_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: adminadmin
      HOST: '0.0.0.0'



  db:
    image: mysql
    environment:
      MYSQL_DATABASE: football_players_db
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_USER: root
      MYSQL_PASSWORD: adminadmin
    restart: always
    ports:
      - "3309:3309"

  redis:
    image: "redis:alpine"